/*
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                {/!*next js org link*!/}
                <h1 className={styles.title}>
                    I learn next js in {" "}
                    <Link
                        href="https://nextjs.org/learn/basics/create-nextjs-app?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=next-website">
                        <a>Nextjs.org</a>
                    </Link>
                    {" "} site
                </h1>
                {/!*my create folder and file*!/}
                <h2>
                    Read {"    "}
                    <Link href="/posts/first-post">
                        <a>this page!</a>
                    </Link>
                    {/!*Learn <a href="https://nextjs.org">Next.js!</a>*!/}
                </h2>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <hr/>
                <h3 style={{color: 'red'}}>Start practises</h3>
                <Image
                    src="/isotipo.png"
                    height={144}
                    width={144}
                    alt="Your Name"
                />
                <Link href={"/posts/HelloWorld"}>
                    <a>HelloWorld</a>
                </Link>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
*/


import Head from 'next/head'
import Layout, { siteTitle } from '../components/layout'
import utilStyles from '../styles/utils.module.css'

export default function Home() {
    return (
        <Layout home>
            <Head>
                <title>{siteTitle}</title>
            </Head>
            <section className={utilStyles.headingMd}>
                <p>[Your Self Introduction]</p>
                <p>
                    (This is a sample website - you’ll be building a site like this on{' '}
                    <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
                </p>
            </section>
        </Layout>
    )
}